<a href="https://colab.research.google.com/github/pandeyp84/python/blob/main/Naive_Baiyse_Classifier_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
#Let's download the iris dataset from its weblink as followes:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

Now, assign the column names to the dataset as follows

In [11]:
headernames = ['sepal-length','sepal-width', 'petal-length', 'petal-width','Class']

In [12]:
#Next we have to read the dataset using the pandas data frame as follows
data = pd.read_csv(path, names=headernames)
data.shape

(150, 5)

In [14]:
#Now, observe the data
data.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
#Let's implement the very basic setp of data pre-processing
X=data.iloc[:,:-1]
y=data.iloc[:,4].values

Here, we are dividing the data into train and test split, with 70% of the training data and 30% of the testing data.

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 )

Let's do the data scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

Now, we are training the model with the model with the help of GaussianNB class of sklearn as follows:

In [21]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train);

Now we have to make the prediction which can be done in the following way:

In [22]:
y_pred = classifier.predict(X_test)

Let's print the result as follows:

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix :")
print(result)
result1=classification_report(y_test, y_pred)
print(result1)
result2=accuracy_score(y_test,y_pred)
print("Accuracy:", result2)

Confusion Matrix :
[[11  0  0]
 [ 0 14  0]
 [ 0  1 19]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      1.00      0.97        14
 Iris-virginica       1.00      0.95      0.97        20

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

Accuracy: 0.9777777777777777
